Repository emylincon/aws_quota_exporter, pull requests merged in 2023-04, with the labels that each got.

#25 add options for specifying aws creds
  README.md
  Taskfile.yaml
  main.go
  pkg/scrape/scrapper.go
Labels: feature

#28 Readme update
  README.md
Labels: documentation

#29 collect default quotas too
  pkg/collector.go
  pkg/scrape/scrapper.go
Labels: feature

#33 add readme
  README.md
Labels: documentation

#34 add go releaser
  .github/workflows/releaser.yml
  .gitignore
  .goreleaser.yaml
  Taskfile.yaml
  docker-compose.yml
  docker/Dockerfile
Labels: enhancement, feature

#35 update releaser
  .github/workflows/releaser.yml
Labels: bug

#48 update dockerfile
  .dockerignore
  README.md
  docker-compose.yml
  docker/Dockerfile
  docker/grafana/dashboards/quotas.json
  docker/prometheus/prometheus.yml
  img/grafana.png
  main.go
Labels: enhancement

#54 Create codeql.yml
  .github/workflows/codeql.yml
Labels: enhancement

#55 request pagination
  pkg/scrapper.go
Labels: enhancement

#56 Enhancement/use go concurrency
  Taskfile.yaml
  pkg/scrapper.go
Labels: enhancement

#58 update readme
  README.md
Labels: documentation

#62 file changes detect
  .github/workflows/codeql.yml
  .github/workflows/go.yml
Labels: enhancement

#63 go fuzz
  Taskfile.yaml
  pkg/cache_test.go
Labels: enhancement

#65 readme update
  README.md
Labels: documentation

#67 prepare release v0.0.1
  .github/workflows/docker.yml
  .goreleaser.yaml
  main.go
Labels: enhancement

#71 badge update
  README.md
Labels: documentation

#77 refactor help page
  README.md
  main.go
  pkg/log.go
  pkg/log_test.go
Labels: enhancement

#80 bug fix data.err
  pkg/scrapper.go
  pkg/scrapper_test.go
Labels: bug

#82 scrapper test
  pkg/scrapper_test.go
Labels: enhancement

#86 job role
  README.md
  Taskfile.yaml
  go.mod
  go.sum
  main.go
  pkg/config.go
  pkg/scrapper.go
  pkg/scrapper_test.go
Labels: feature

#88 release v0.1.0
  main.go
  pkg/scrapper.go
Labels: enhancement, feature

#90 scrapper
  pkg/scrapper.go
Labels: bug, documentation

#92 taskfile update
  Taskfile.yaml
Labels: feature

#93 Add kubernetes manifest files
  .pre-commit-config.yaml
  Taskfile.yaml
  kubernetes/aws_quota_exporter.yaml
  kubernetes/grafana.yaml
  kubernetes/prometheus.yaml
Labels: feature
